INSERT INTO Categories (Name)
VALUES ('Dog')
INSERT INTO Categories (Name)
VALUES ('Cat')
INSERT INTO Categories (Name)
VALUES ('Hog')
INSERT INTO Categories (Name)
VALUES ('Lizard')
INSERT INTO Categories (Name)
VALUES ('Bat')

INSERT INTO DietPlans (Name, FoodType, FoodAmountInCups)
VALUES ('DogDietPlan', 'dogfood', '3')
INSERT INTO DietPlans (Name, FoodType, FoodAmountInCups)
VALUES ('CatDietPlan', 'catfood', '2')
INSERT INTO DietPlans (Name, FoodType, FoodAmountInCups)
VALUES ('HogDietPlan', 'hogfood', '5')
INSERT INTO DietPlans (Name, FoodType, FoodAmountInCups)
VALUES ('LizardDietPlan', 'lizardfood', '1')
INSERT INTO DietPlans (Name, FoodType, FoodAmountInCups)
VALUES ('BatDietPlan', 'blood', '1')

INSERT INTO Animals (Name, Weight, Age, Demeanor, KidFriendly, PetFriendly, Gender, AdoptionStatus, CategoryId, DietPlanId, EmployeeId)
VALUES ('Max', 85, 7, 'friendly', 1, 1, 'male', 'adoptable', 1, 1, 1)
INSERT INTO Animals (Name, Weight, Age, Demeanor, KidFriendly, PetFriendly, Gender, AdoptionStatus, CategoryId, DietPlanId, EmployeeId)
VALUES ('Garfield', 35, 42, 'lazy', 0, 0, 'male', 'adoptable', 2, 2, 2)
INSERT INTO Animals (Name, Weight, Age, Demeanor, KidFriendly, PetFriendly, Gender, AdoptionStatus, CategoryId, DietPlanId, EmployeeId)
VALUES ('Poomba', 230, 5, 'comical', 1, 0, 'male', 'nonadoptable', 3, 3, 3)
INSERT INTO Animals (Name, Weight, Age, Demeanor, KidFriendly, PetFriendly, Gender, AdoptionStatus, CategoryId, DietPlanId, EmployeeId)
VALUES ('Larry', 2, 11, 'unfriendly', 0, 0, 'female', 'nonadoptable', 4, 4, 4)
INSERT INTO Animals (Name, Weight, Age, Demeanor, KidFriendly, PetFriendly, Gender, AdoptionStatus, CategoryId, DietPlanId, EmployeeId)
VALUES ('Dracula', 5, 1000, 'vicious', 0, 0, 'female', 'nonadoptable', 5, 5, 5)



INSERT INTO Employees (FirstName, LastName, UserName, Password, EmployeeNumber, Email)
VALUES ('Billy', 'Bob', 'billyBob', 'bobspassword', '1', 'bob@myemail.com')
INSERT INTO Employees (FirstName, LastName, UserName, Password, EmployeeNumber, Email)
VALUES ('Frederick', 'Jones', 'FJones', 'fjonespassword', '2', 'jones@myemail.com')
INSERT INTO Employees (FirstName, LastName, UserName, Password, EmployeeNumber, Email)
VALUES ('Jill', 'Thomas', 'jillTheThrill', 'jillspassword', '3', 'jillthrill@myemail.com')
INSERT INTO Employees (FirstName, LastName, UserName, Password, EmployeeNumber, Email)
VALUES ('Candace', 'Applebottom', 'applebottom', 'applebottompassword', '4', 'applebottom@myemail.com')
INSERT INTO Employees (FirstName, LastName, UserName, Password, EmployeeNumber, Email)
VALUES ('Stella', 'Bob', 'stellaBob', 'stellaspassword', '5', 'stella@myemail.com')

INSERT INTO Rooms (RoomNumber, AnimalId)
VALUES (255, 1)
INSERT INTO Rooms (RoomNumber, AnimalId)
VALUES (312, 1)
INSERT INTO Rooms (RoomNumber, AnimalId)
VALUES (214, 2)
INSERT INTO Rooms (RoomNumber, AnimalId)
VALUES (432, 2)
INSERT INTO Rooms (RoomNumber, AnimalId)
VALUES (246, 3)
INSERT INTO Rooms (RoomNumber, AnimalId)
VALUES (113, 3)
INSERT INTO Rooms (RoomNumber, AnimalId)
VALUES (256, 4)
INSERT INTO Rooms (RoomNumber, AnimalId)
VALUES (284, 4)
INSERT INTO Rooms (RoomNumber, AnimalId)
VALUES (742, 5)
INSERT INTO Rooms (RoomNumber, AnimalId)
VALUES (475, 5)

INSERT INTO Clients (FirstName, LastName, UserName, Password, AddressId, Email)
VALUES ('Tim', 'Buckly', 'timmyb', 'timmyspassword', 1, 'timmy@myemail.com')
INSERT INTO Clients (FirstName, LastName, UserName, Password, AddressId, Email)
VALUES ('Bim', 'Jim', 'bimmyj', 'bimmyspassword', 2, 'bimmy@myemail.com')
INSERT INTO Clients (FirstName, LastName, UserName, Password, AddressId, Email)
VALUES ('Kim', 'Tuckly', 'kimmyt', 'kimmyspassword', 3, 'kimmy@myemail.com')
INSERT INTO Clients (FirstName, LastName, UserName, Password, AddressId, Email)
VALUES ('Freddy', 'Kreuger', 'nightmarekiller', 'freddysspassword', 4, 'freddy@myemail.com')
INSERT INTO Clients (FirstName, LastName, UserName, Password, AddressId, Email)
VALUES ('Eleanor', 'Rigby', 'ellarig', 'eleanorsspassword', 5, 'rigby@myemail.com')


INSERT INTO Addresses (AddressLine1, City, USStateId, Zipcode)
VALUES ('123 Main St.', 'Charleston', 33, 94823)
INSERT INTO Addresses (AddressLine1, City, USStateId, Zipcode)
VALUES ('456 Easy St.', 'Kalamazoo', 26, 22357)
INSERT INTO Addresses (AddressLine1, City, USStateId, Zipcode)
VALUES ('789 Ice Cream St.', 'Los Angeles', 5, 90210)
INSERT INTO Addresses (AddressLine1, City, USStateId, Zipcode)
VALUES ('712 Elm St.', 'Springwood', 35, 47532)
INSERT INTO Addresses (AddressLine1, City, USStateId, Zipcode)
VALUES ('513 Scenic Ave.', 'Podunk', 17, 55555)
